DROP TABLE IF EXISTS category CASCADE;
DROP INDEX IF EXISTS category_name_idx;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS product_name_idx;

CREATE TABLE IF NOT EXISTS category
(
	id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name VARCHAR(50) UNIQUE                      NOT NULL,
	CONSTRAINT pk_category PRIMARY KEY (id)
);
CREATE UNIQUE INDEX category_name_idx ON category USING btree (name);


CREATE TABLE IF NOT EXISTS product
(
	id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name        VARCHAR(255) UNIQUE                     NOT NULL,
	description VARCHAR(1000)                           NOT NULL,
	price       NUMERIC(19, 2)                          NOT NULL,
	category_id BIGINT                                  NOT NULL,
	CONSTRAINT pk_product PRIMARY KEY (id),
	CONSTRAINT fk_product_to_category FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX product_name_idx ON product USING btree (name);